CREATE DATABASE CompanyDB;
USE CompanyDB;

CREATE TABLE Employees (
    EmployeeID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);

ALTER TABLE Employees ADD COLUMN HireDate DATE;
ALTER TABLE Employees ADD COLUMN Salary INT;
